### PR TITLE
Allow multiple randomly-selected songs for an event

### PR DESCRIPTION
**Pull request by Samuel-Harbord**
I made this modification mostly for my own use but I saw someone else requesting this same feature so I made it a pull request. I may not have chosen the most efficient method to add this functionality so, if you choose to use this pull request, you may want to make your own adjustments before adding it. I worked out all the bugs I could find but there may be minor bugs present that I haven't found.

Commit Description:

Multiple song names can be provided for each event by separating the song names with a comma ',' in the properties file. When a song for the event should load, it will randomly load one of the songs but it will not play the same song twice in a row.

NOTE: This commit introduces a new song name limitation that song names should not contain the exact
names of any other song names as this will cause conflicts.

### CODE REVIEW

**Comment by Samuel-Harbord** [comment]
Bug that I found: Next Song text in debug doesn't disappear when going to a different event then going back to the first one and may not reflect the song that plays when going back to the second one again. It also seems to be more insistent on changing the song when going to a different event and does not return to the first song as easily. If I fix this, I will also post that here.

**Comment by Samuel-Harbord** [comment]
Another bug: Music does not resume after turning off the volume until a new event is triggered.

**Comment by Samuel-Harbord** [comment]
Bug: When the game is not focused and the song transitions to a different song, the song transitions out just after starting and starts again before playing all the way through.

**Comment by Namnodorel** [comment]
Thank you, I needed those features/bug fixes! Please merge it @Vazkii until then I'll use the fork of Samuel-Harbord

**Comment by Vazkii** [comment]
When I find some time I need to redo ambience from scratch. Until then I really don't have the time to maintain it. You're more than welcome to use the fork.

**Comment by Samuel-Harbord** [comment]
@Namnodorel Here is a build if you haven't already done it yourself. http://www.mediafire.com/download/s1cswgzptrmbih4/Ambience_1.0-8.jar

**Comment by Namnodorel** [comment]
Oh thank you! I have actually tried to build it already, but ran into some issues, probably because I don't have anything set up for developing mods. I'd have looked further into it tomorrow, but if you have a build ready that's even better than me messing with other peoples code :D

**Comment by Namnodorel** [comment]
Uhm, that songpicking doesn't work as well as I thought...

`java.lang.NullPointerException: Unexpected error
	at vazkii.ambience.SongPicker.getRandomSong(SongPicker.java:240)
	at vazkii.ambience.Ambience.onTick(Ambience.java:81)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_Ambience_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Where my ambience.properties is just
`# Ambience Config

enabled=true

# === Events - Highest Priority
# Any non covered events will be ignored
# e.g. If you don't want a "high up" song, don't include event.highUp

#event.mainMenu=
#event.boss=
#event.underground=
#event.deepUnderground=
#event.highUp=
#event.village=
#event.underwater=
#event.minecart=
#event.boat=
#event.horse=
#event.pig=
#event.night=
#event.rain=
#event.dying=
#event.fishing=
#event.pumpkinHead=
event.generic=IntoTheMindsEye,TheJourneyHome

# === Events End

# === Specific Biomes - High Priority
# Biomes names have spaces replaced with +

#biome.Sunflower+Plains=
#biome.Flower+Forest=
#biome.Roofed+Forest=
#biome.Deep+Ocean=

# === Specific Biomes End

# === Biome Tags - Medium/Low Priority
# These make use of the forge biome dictionary
# Casing is ignored
# There's primary and secondary tags. All primary tags will get checked before the secondary ones
# https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/BiomeDictionary.java

# Medium priority
#primarytag.spooky=
#primarytag.dead=
#primarytag.lush=
#primarytag.nether=
#primarytag.end=
#primarytag.mushroom=
#primarytag.magical=
#primarytag.ocean=
#primarytag.river=

# Low
#secondarytag.mesa=
#secondarytag.forest=
#secondarytag.plains=
#secondarytag.moutain=
#secondarytag.hills=
#secondarytag.swamp=
#secondarytag.sandy=
#secondarytag.snowy=
#secondarytag.wasteland=
#secondarytag.beach=

# === Biome Tags End
`

(I commented so much out because I wanted to work slowly towards a completed config)

**Comment by Samuel-Harbord** [comment]
Issues are enabled now so you can take this issue there. Also, if you could confirm that this only happens on my fork and not the original, that would be very helpful.

**Comment by Samuel-Harbord** [comment]
I guess you won't have to, I fixed it. Here is an updated build: http://www.mediafire.com/file/m8k0ju35x1v1mzl/Ambience_1.0-9.jar

**Comment by Iteries** [comment]
Only thing I see after all this = Update to curse forge for downloading and reflect it on the code for bases.. ie the config for how-to add your own music modifications.  I have some old Dungeon Keeper music/quotes like to add-to music grouping that this update offers.   THANK YOU  Namnodorel & Samuel for all your hard work and time.

**Comment by P3rf3ctXZer0** [comment]
I too am testing this.

**Comment by CircuitLord** [comment]
Read the comments for this after I downloaded forge and setup a compiling workspace and compiled the mod. Great going me. At least I learned a bit about forge compiling lol.

**Pull request merged**
